/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedRepairsIndexRouteImport } from './routes/_authed/repairs/index'
import { Route as AuthedCustomersIndexRouteImport } from './routes/_authed/customers/index'
import { Route as AuthedRepairsRepairIdRouteImport } from './routes/_authed/repairs/$repairId'
import { Route as AuthedCustomersCustomerIdRouteImport } from './routes/_authed/customers/$customerId'
import { Route as AuthedCarsCarIdRouteImport } from './routes/_authed/cars/$carId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRepairsIndexRoute = AuthedRepairsIndexRouteImport.update({
  id: '/repairs/',
  path: '/repairs/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersIndexRoute = AuthedCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRepairsRepairIdRoute = AuthedRepairsRepairIdRouteImport.update({
  id: '/repairs/$repairId',
  path: '/repairs/$repairId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersCustomerIdRoute =
  AuthedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCarsCarIdRoute = AuthedCarsCarIdRouteImport.update({
  id: '/cars/$carId',
  path: '/cars/$carId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/cars/$carId': typeof AuthedCarsCarIdRoute
  '/customers/$customerId': typeof AuthedCustomersCustomerIdRoute
  '/repairs/$repairId': typeof AuthedRepairsRepairIdRoute
  '/customers/': typeof AuthedCustomersIndexRoute
  '/repairs/': typeof AuthedRepairsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/cars/$carId': typeof AuthedCarsCarIdRoute
  '/customers/$customerId': typeof AuthedCustomersCustomerIdRoute
  '/repairs/$repairId': typeof AuthedRepairsRepairIdRoute
  '/customers': typeof AuthedCustomersIndexRoute
  '/repairs': typeof AuthedRepairsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/cars/$carId': typeof AuthedCarsCarIdRoute
  '/_authed/customers/$customerId': typeof AuthedCustomersCustomerIdRoute
  '/_authed/repairs/$repairId': typeof AuthedRepairsRepairIdRoute
  '/_authed/customers/': typeof AuthedCustomersIndexRoute
  '/_authed/repairs/': typeof AuthedRepairsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/cars/$carId'
    | '/customers/$customerId'
    | '/repairs/$repairId'
    | '/customers/'
    | '/repairs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/cars/$carId'
    | '/customers/$customerId'
    | '/repairs/$repairId'
    | '/customers'
    | '/repairs'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/dashboard'
    | '/_authed/cars/$carId'
    | '/_authed/customers/$customerId'
    | '/_authed/repairs/$repairId'
    | '/_authed/customers/'
    | '/_authed/repairs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/repairs/': {
      id: '/_authed/repairs/'
      path: '/repairs'
      fullPath: '/repairs/'
      preLoaderRoute: typeof AuthedRepairsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/': {
      id: '/_authed/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthedCustomersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/repairs/$repairId': {
      id: '/_authed/repairs/$repairId'
      path: '/repairs/$repairId'
      fullPath: '/repairs/$repairId'
      preLoaderRoute: typeof AuthedRepairsRepairIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/$customerId': {
      id: '/_authed/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cars/$carId': {
      id: '/_authed/cars/$carId'
      path: '/cars/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof AuthedCarsCarIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedCarsCarIdRoute: typeof AuthedCarsCarIdRoute
  AuthedCustomersCustomerIdRoute: typeof AuthedCustomersCustomerIdRoute
  AuthedRepairsRepairIdRoute: typeof AuthedRepairsRepairIdRoute
  AuthedCustomersIndexRoute: typeof AuthedCustomersIndexRoute
  AuthedRepairsIndexRoute: typeof AuthedRepairsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedCarsCarIdRoute: AuthedCarsCarIdRoute,
  AuthedCustomersCustomerIdRoute: AuthedCustomersCustomerIdRoute,
  AuthedRepairsRepairIdRoute: AuthedRepairsRepairIdRoute,
  AuthedCustomersIndexRoute: AuthedCustomersIndexRoute,
  AuthedRepairsIndexRoute: AuthedRepairsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
