/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTeamRouteImport } from './routes/_authed/team'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedRepairsIndexRouteImport } from './routes/_authed/repairs/index'
import { Route as AuthedOffersIndexRouteImport } from './routes/_authed/offers/index'
import { Route as AuthedCustomersIndexRouteImport } from './routes/_authed/customers/index'
import { Route as AuthedCarsIndexRouteImport } from './routes/_authed/cars/index'
import { Route as AuthedRepairsRepairIdRouteImport } from './routes/_authed/repairs/$repairId'
import { Route as AuthedCustomersCustomerIdRouteImport } from './routes/_authed/customers/$customerId'
import { Route as AuthedCarsCarIdRouteImport } from './routes/_authed/cars/$carId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTeamRoute = AuthedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRepairsIndexRoute = AuthedRepairsIndexRouteImport.update({
  id: '/repairs/',
  path: '/repairs/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOffersIndexRoute = AuthedOffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersIndexRoute = AuthedCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCarsIndexRoute = AuthedCarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRepairsRepairIdRoute = AuthedRepairsRepairIdRouteImport.update({
  id: '/repairs/$repairId',
  path: '/repairs/$repairId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersCustomerIdRoute =
  AuthedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCarsCarIdRoute = AuthedCarsCarIdRouteImport.update({
  id: '/cars/$carId',
  path: '/cars/$carId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/team': typeof AuthedTeamRoute
  '/cars/$carId': typeof AuthedCarsCarIdRoute
  '/customers/$customerId': typeof AuthedCustomersCustomerIdRoute
  '/repairs/$repairId': typeof AuthedRepairsRepairIdRoute
  '/cars/': typeof AuthedCarsIndexRoute
  '/customers/': typeof AuthedCustomersIndexRoute
  '/offers/': typeof AuthedOffersIndexRoute
  '/repairs/': typeof AuthedRepairsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/team': typeof AuthedTeamRoute
  '/cars/$carId': typeof AuthedCarsCarIdRoute
  '/customers/$customerId': typeof AuthedCustomersCustomerIdRoute
  '/repairs/$repairId': typeof AuthedRepairsRepairIdRoute
  '/cars': typeof AuthedCarsIndexRoute
  '/customers': typeof AuthedCustomersIndexRoute
  '/offers': typeof AuthedOffersIndexRoute
  '/repairs': typeof AuthedRepairsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/team': typeof AuthedTeamRoute
  '/_authed/cars/$carId': typeof AuthedCarsCarIdRoute
  '/_authed/customers/$customerId': typeof AuthedCustomersCustomerIdRoute
  '/_authed/repairs/$repairId': typeof AuthedRepairsRepairIdRoute
  '/_authed/cars/': typeof AuthedCarsIndexRoute
  '/_authed/customers/': typeof AuthedCustomersIndexRoute
  '/_authed/offers/': typeof AuthedOffersIndexRoute
  '/_authed/repairs/': typeof AuthedRepairsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/team'
    | '/cars/$carId'
    | '/customers/$customerId'
    | '/repairs/$repairId'
    | '/cars/'
    | '/customers/'
    | '/offers/'
    | '/repairs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/team'
    | '/cars/$carId'
    | '/customers/$customerId'
    | '/repairs/$repairId'
    | '/cars'
    | '/customers'
    | '/offers'
    | '/repairs'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authed/dashboard'
    | '/_authed/team'
    | '/_authed/cars/$carId'
    | '/_authed/customers/$customerId'
    | '/_authed/repairs/$repairId'
    | '/_authed/cars/'
    | '/_authed/customers/'
    | '/_authed/offers/'
    | '/_authed/repairs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/team': {
      id: '/_authed/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthedTeamRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/repairs/': {
      id: '/_authed/repairs/'
      path: '/repairs'
      fullPath: '/repairs/'
      preLoaderRoute: typeof AuthedRepairsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/offers/': {
      id: '/_authed/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof AuthedOffersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/': {
      id: '/_authed/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthedCustomersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cars/': {
      id: '/_authed/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof AuthedCarsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/repairs/$repairId': {
      id: '/_authed/repairs/$repairId'
      path: '/repairs/$repairId'
      fullPath: '/repairs/$repairId'
      preLoaderRoute: typeof AuthedRepairsRepairIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/$customerId': {
      id: '/_authed/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cars/$carId': {
      id: '/_authed/cars/$carId'
      path: '/cars/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof AuthedCarsCarIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedTeamRoute: typeof AuthedTeamRoute
  AuthedCarsCarIdRoute: typeof AuthedCarsCarIdRoute
  AuthedCustomersCustomerIdRoute: typeof AuthedCustomersCustomerIdRoute
  AuthedRepairsRepairIdRoute: typeof AuthedRepairsRepairIdRoute
  AuthedCarsIndexRoute: typeof AuthedCarsIndexRoute
  AuthedCustomersIndexRoute: typeof AuthedCustomersIndexRoute
  AuthedOffersIndexRoute: typeof AuthedOffersIndexRoute
  AuthedRepairsIndexRoute: typeof AuthedRepairsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedTeamRoute: AuthedTeamRoute,
  AuthedCarsCarIdRoute: AuthedCarsCarIdRoute,
  AuthedCustomersCustomerIdRoute: AuthedCustomersCustomerIdRoute,
  AuthedRepairsRepairIdRoute: AuthedRepairsRepairIdRoute,
  AuthedCarsIndexRoute: AuthedCarsIndexRoute,
  AuthedCustomersIndexRoute: AuthedCustomersIndexRoute,
  AuthedOffersIndexRoute: AuthedOffersIndexRoute,
  AuthedRepairsIndexRoute: AuthedRepairsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
